### ISSUE TITLE
Update!

### ISSUE THREAD

**Issue by Alaneczek123123851** [ashenafee/SteamUL#1]
Please update it, it's been an whole year!

**Comment by ashenafee** [comment]
I've been working on a new version for a little while, but because of midterms and everything, it's been delayed. Once things are back on track with school, I'll upload the reworked version (which at this point would be an entirely new program) and reply to this Issue!

It's just been iffy to test because running PyQt on an Apple Silicon device has been giving me trouble, so I've had to leave development on an old Linux box. Hopefully I can figure out the PyQt issue to speed up development again.

**Comment by Alaneczek123123851** [comment]
i can test it for u, add on discord Zionek#0001
